/*
 * Veritas Information Classifier (VIC)
 * APIs
 *
 * OpenAPI spec version: Resource Specific
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ErrorResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-12T23:38:16.514Z")
public class ErrorResponse {
  @SerializedName("statusCode")
  private Integer statusCode = null;

  @SerializedName("message")
  private String message = null;

  /**
   * Gets or Sets error
   */
  public enum ErrorEnum {
    @SerializedName("SERVER_ERROR")
    SERVER_ERROR("SERVER_ERROR"),
    
    @SerializedName("CLIENT_ERROR")
    CLIENT_ERROR("CLIENT_ERROR"),
    
    @SerializedName("NO_POLICIES_ENABLED")
    NO_POLICIES_ENABLED("NO_POLICIES_ENABLED"),
    
    @SerializedName("NO_POLICIES_LOADED")
    NO_POLICIES_LOADED("NO_POLICIES_LOADED"),
    
    @SerializedName("UNKNOWN_POLICY")
    UNKNOWN_POLICY("UNKNOWN_POLICY"),
    
    @SerializedName("CLIENT_FILE_NOT_FOUND")
    CLIENT_FILE_NOT_FOUND("CLIENT_FILE_NOT_FOUND"),
    
    @SerializedName("CONTENT_TOO_LARGE")
    CONTENT_TOO_LARGE("CONTENT_TOO_LARGE"),
    
    @SerializedName("TAG_PROPERTY_DEFINITIONS_UNAVAILABLE")
    TAG_PROPERTY_DEFINITIONS_UNAVAILABLE("TAG_PROPERTY_DEFINITIONS_UNAVAILABLE");

    private String value;

    ErrorEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("error")
  private ErrorEnum error = null;

  public ErrorResponse statusCode(Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }

  public ErrorResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ErrorResponse error(ErrorEnum error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(example = "null", value = "")
  public ErrorEnum getError() {
    return error;
  }

  public void setError(ErrorEnum error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponse errorResponse = (ErrorResponse) o;
    return Objects.equals(this.statusCode, errorResponse.statusCode) &&
        Objects.equals(this.message, errorResponse.message) &&
        Objects.equals(this.error, errorResponse.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusCode, message, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponse {\n");
    
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

